// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoCB4OmlPiycSgTjcsO5y63VXY55wBEo',
    appId: '1:602418220767:web:cef8a1f53572af136de36a',
    messagingSenderId: '602418220767',
    projectId: 'appoint-it-4567',
    authDomain: 'appoint-it-4567.firebaseapp.com',
    storageBucket: 'appoint-it-4567.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmRK8k1_L4zcj75e__uQ0MZByaFuv48w',
    appId: '1:602418220767:android:858454ae023e92f76de36a',
    messagingSenderId: '602418220767',
    projectId: 'appoint-it-4567',
    storageBucket: 'appoint-it-4567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd05XbA8EqMagnJFmO067gJQh8fOlbavk',
    appId: '1:602418220767:ios:c47578fbee0ba4b16de36a',
    messagingSenderId: '602418220767',
    projectId: 'appoint-it-4567',
    storageBucket: 'appoint-it-4567.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd05XbA8EqMagnJFmO067gJQh8fOlbavk',
    appId: '1:602418220767:ios:c47578fbee0ba4b16de36a',
    messagingSenderId: '602418220767',
    projectId: 'appoint-it-4567',
    storageBucket: 'appoint-it-4567.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoCB4OmlPiycSgTjcsO5y63VXY55wBEo',
    appId: '1:602418220767:web:64f0c873a3f781c26de36a',
    messagingSenderId: '602418220767',
    projectId: 'appoint-it-4567',
    authDomain: 'appoint-it-4567.firebaseapp.com',
    storageBucket: 'appoint-it-4567.firebasestorage.app',
  );
}
